param([switch]$Install,[switch]$Uninstall,[switch]$Once,[int]$PollSeconds=5,[int]$StableSeconds=20,[int]$GitAttempts=5)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$TaskLabel='Guardian Backtest CSV AutoSync v2.01 GENERIC PUBLICSAFE'
$InstallDir='D:\MT5_Backtests\automation';$InstalledFile=Join-Path $InstallDir 'Guardian_Backtest_CSV_AutoSync_v2_01_GENERIC_PUBLICSAFE.ps1'
$StartupDir=Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs\Startup';$StartupCmd=Join-Path $StartupDir 'Guardian_Backtest_CSV_AutoSync_v2_01.cmd'
$PidFile='D:\MT5_Backtests\guardian-backtest-csv-sync-v201.pid';$StateFile='D:\MT5_Backtests\guardian-backtest-csv-sync-v201-state.json';$HealthFile='D:\MT5_Backtests\guardian-backtest-csv-sync-v201-health.json';$LogFile='D:\MT5_Backtests\logs\guardian-backtest-csv-sync-v201.log'
$ResultsClone='D:\MT5_Backtests\guardian-backtest-autosync-results';$ResultsBranch='backtest-results';$RepoRoot='D:\MT5_Backtests\guardian-research';$RemoteFallback='https://github.com/yum4nity-code/guardian-research.git';$CommonFiles=Join-Path $env:APPDATA 'MetaQuotes\Terminal\Common\Files'
$OldStartup=@((Join-Path $StartupDir 'Guardian_D023_CSV_AutoSync_v1_04.cmd'),(Join-Path $StartupDir 'Guardian_Backtest_CSV_AutoSync_v2_00.cmd'));$OldPid=@('D:\MT5_Backtests\guardian-d023-csv-sync-v104.pid','D:\MT5_Backtests\guardian-backtest-csv-sync-v200.pid')
function EP([string]$p){$q=Split-Path -Parent $p;if($q -and -not(Test-Path $q)){New-Item -ItemType Directory -Force -Path $q|Out-Null}}
function Log([string]$m){EP $LogFile;$l='{0} | {1}' -f ([DateTime]::Now.ToString('yyyy-MM-dd HH:mm:ss')),$m;Add-Content $LogFile $l -Encoding UTF8;if(-not $Install){Write-Host $l}}
function Health([string]$s,[string]$m,[string]$f=''){EP $HealthFile;[ordered]@{schema=2;watcher=$TaskLabel;updated_at_utc=[DateTime]::UtcNow.ToString('o');status=$s;message=$m;last_file=$f;common_files=$CommonFiles;results_branch=$ResultsBranch}|ConvertTo-Json -Depth 4|Set-Content "$HealthFile.tmp" -Encoding UTF8;Move-Item "$HealthFile.tmp" $HealthFile -Force}
function QA([string]$v){if($null -eq $v -or $v.Length -eq 0){return '""'};if($v -notmatch '[\s"]'){return $v};return '"'+($v -replace '(\\*)"','$1$1\"' -replace '(\\+)$','$1$1')+'"'}
function G1([string[]]$GitArgs,[switch]$AllowFailure){if(-not $GitArgs -or $GitArgs.Count -eq 0){throw 'empty GitArgs'};$git=(Get-Command git.exe -ErrorAction Stop).Source;$o=Join-Path $env:TEMP ("g_o_{0}_{1}.txt" -f $PID,[guid]::NewGuid().ToString('N'));$e=Join-Path $env:TEMP ("g_e_{0}_{1}.txt" -f $PID,[guid]::NewGuid().ToString('N'));try{$line=(($GitArgs|ForEach-Object{QA $_}) -join ' ');$p=Start-Process $git -ArgumentList $line -NoNewWindow -Wait -PassThru -RedirectStandardOutput $o -RedirectStandardError $e;$so=if(Test-Path $o){@(Get-Content $o -ErrorAction SilentlyContinue)}else{@()};$se=if(Test-Path $e){@(Get-Content $e -ErrorAction SilentlyContinue)}else{@()};$all=@($so)+@($se);if($p.ExitCode -ne 0 -and -not $AllowFailure){throw "git $($GitArgs -join ' ') failed ($($p.ExitCode)): $($all -join ' ')"};[pscustomobject]@{Code=$p.ExitCode;StdOut=@($so);Output=@($all)}}finally{Remove-Item $o,$e -Force -ErrorAction SilentlyContinue}}
function GR([string[]]$GitArgs){$n=[Math]::Max(1,$GitAttempts);for($i=1;$i -le $n;$i++){$r=G1 -GitArgs $GitArgs -AllowFailure;if($r.Code -eq 0){return $r};if($i -eq $n){throw "git failed after $n attempts: $($r.Output -join ' ')"};Start-Sleep ([int][Math]::Min(60,[Math]::Pow(2,$i)))}}
function Remote{if(Test-Path (Join-Path $RepoRoot '.git')){try{$r=G1 -GitArgs @('-C',$RepoRoot,'remote','get-url','origin');$u=(($r.StdOut|Select-Object -First 1).ToString()).Trim();if($u){return $u}}catch{}};$RemoteFallback}
function Clone{if(-not(Get-Command git.exe -ErrorAction SilentlyContinue)){throw 'git.exe introuvable'};if(-not(Test-Path (Join-Path $ResultsClone '.git'))){if(Test-Path $ResultsClone){Move-Item $ResultsClone "$ResultsClone.bad.$([DateTime]::Now.ToString('yyyyMMdd_HHmmss'))"};GR -GitArgs @('clone','--quiet','--branch',$ResultsBranch,'--single-branch',(Remote),$ResultsClone)|Out-Null};$d=G1 -GitArgs @('-C',$ResultsClone,'status','--porcelain');if(@($d.StdOut).Count -gt 0){GR -GitArgs @('-C',$ResultsClone,'add','-A')|Out-Null;$c=G1 -GitArgs @('-C',$ResultsClone,'commit','-m','Recover pending generic autosync transaction') -AllowFailure;if($c.Code -eq 0){GR -GitArgs @('-C',$ResultsClone,'push','origin',$ResultsBranch)|Out-Null}};GR -GitArgs @('-C',$ResultsClone,'pull','--rebase','origin',$ResultsBranch)|Out-Null}
function H([string]$p){(Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant()};function S([string]$p){$f=Get-Item $p;'{0}|{1}' -f $f.Length,$f.LastWriteTimeUtc.Ticks}
function FP([string]$a,[string]$b){$x="$a|$(H $a)|$b|$(H $b)";$q=[Security.Cryptography.SHA256]::Create();try{(($q.ComputeHash([Text.Encoding]::UTF8.GetBytes($x))|ForEach-Object{$_.ToString('x2')}) -join '')}finally{$q.Dispose()}}
function LS{if(Test-Path $StateFile){try{return Get-Content $StateFile -Raw|ConvertFrom-Json}catch{}};[pscustomobject]@{schema=2;watch_start_utc=[DateTime]::UtcNow.ToString('o');published_fingerprints=@()}}
function SS($s){EP $StateFile;$s|ConvertTo-Json -Depth 8|Set-Content "$StateFile.tmp" -Encoding UTF8;Move-Item "$StateFile.tmp" $StateFile -Force};function IP($s,[string]$f){@($s.published_fingerprints) -contains $f};function MP($s,[string]$f){$s.published_fingerprints=@((@($s.published_fingerprints)+@($f))|Select-Object -Unique);SS $s}
function VP([string]$sp,[string]$tp){$ss=@(Import-Csv $sp -Delimiter ';');if($ss.Count -lt 3){throw 'STATS incomplete'};$st=@($ss|ForEach-Object{$_.status});$i=[Array]::IndexOf($st,'INIT');$r=[Array]::IndexOf($st,'READY');$f=[Array]::LastIndexOf($st,'FINAL');if($i -lt 0 -or $r -lt 0 -or $f -lt 0 -or -not($i -lt $r -and $r -lt $f)){throw 'require INIT -> READY -> FINAL'};$z=$ss[$f];foreach($x in @('source_name','source_version','symbol','timeframe','trades_closed','csv_trade_rows')){if(-not($z.PSObject.Properties.Name -contains $x) -or -not $z.$x){throw "missing final field $x"}};$closed=0;$rows=0;if(-not[int]::TryParse($z.trades_closed,[ref]$closed)){throw 'invalid trades_closed'};if(-not[int]::TryParse($z.csv_trade_rows,[ref]$rows)){throw 'invalid csv_trade_rows'};if($closed -ne $rows){throw "closed/rows mismatch $closed/$rows"};if($z.PSObject.Properties.Name -contains 'trades_opened'){$opened=0;if(-not[int]::TryParse($z.trades_opened,[ref]$opened)){throw 'invalid trades_opened'};if($opened -ne $closed){throw "opened/closed mismatch $opened/$closed"}};$tt=@(Import-Csv $tp -Delimiter ';');if($tt.Count -ne $closed){throw "TRADES row mismatch $($tt.Count)/$closed"};[pscustomobject]@{Final=$z;Trades=$tt;Closed=$closed}}
function PC([string]$src,[string]$dst,[switch]$Redact){EP $dst;$raw=Get-Content $src -Raw;if($Redact){$raw=[regex]::Replace($raw,'(?i)([A-Z]:\\Users\\)[^\\;,"\r\n]+','$1<REDACTED>')};foreach($rx in @('(?i)password','(?i)api[_-]?key','(?i)secret','(?i)credential','(?i)[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}')){if($raw -match $rx){throw "PUBLICSAFE block $([IO.Path]::GetFileName($src))"}};if($raw -match '(?i)[A-Z]:\\Users\\(?!<REDACTED>)[^\\;,"\r\n]+'){throw 'unredacted Windows user path'};Set-Content $dst $raw -Encoding UTF8}
function Pub([IO.FileInfo]$sf,[string]$tp,$state){$sp=$sf.FullName;$a=S $sp;$b=S $tp;Start-Sleep $StableSeconds;if($a -ne(S $sp)-or$b -ne(S $tp)){return};$h1=H $sp;$h2=H $tp;$v=VP $sp $tp;if($h1 -ne(H $sp)-or$h2 -ne(H $tp)){throw 'outputs changed during validation'};$fp=FP $sp $tp;if(IP $state $fp){return};Clone;$fam=([regex]::Match($sf.Name,'^(D\d{3})_')).Groups[1].Value;if(-not$fam){$fam='DXXX'};$sym=($v.Final.symbol -replace '[^A-Za-z0-9_-]','_');$stamp=$sf.LastWriteTimeUtc.ToString('yyyyMMdd_HHmmss');$run="${stamp}_${fam}_${sym}_$($fp.Substring(0,12))";$rel='backtests/inbox/{0}/{1}/{2}/{3}' -f $sf.LastWriteTimeUtc.ToString('yyyy'),$sf.LastWriteTimeUtc.ToString('MM'),$sf.LastWriteTimeUtc.ToString('dd'),$run;$dest=Join-Path $ResultsClone ($rel -replace '/','\');$man=Join-Path $dest 'sync_manifest.json';if(Test-Path $man){try{$old=Get-Content $man -Raw|ConvertFrom-Json;if($old.fingerprint -eq $fp){GR -GitArgs @('-C',$ResultsClone,'push','origin',$ResultsBranch)|Out-Null;MP $state $fp;Health 'OK' "Recovered existing publication $run" $sf.Name;return}}catch{};throw "deterministic run collision $run"};New-Item -ItemType Directory -Force -Path $dest|Out-Null;$sd=Join-Path $dest $sf.Name;$td=Join-Path $dest ([IO.Path]::GetFileName($tp));PC $sp $sd -Redact;PC $tp $td;$vv=VP $sd $td;$stage=if($v.Final.PSObject.Properties.Name -contains 'run_stage'){$v.Final.run_stage}else{''};[ordered]@{schema=5;run_id=$run;fingerprint=$fp;synced_at_utc=[DateTime]::UtcNow.ToString('o');reason='GENERIC_FINAL_VALIDATED';branch=$ResultsBranch;autosync_version='2.01';validation=[ordered]@{required_status_sequence='INIT -> READY -> FINAL';source_name=$v.Final.source_name;source_version=$v.Final.source_version;run_stage=$stage;symbol=$v.Final.symbol;timeframe=$v.Final.timeframe;trades_closed=$vv.Closed;published_trades_rows=$vv.Trades.Count};files=@([ordered]@{name=$sf.Name;source_sha256=$h1;published_sha256=(H $sd);sanitized=$true},[ordered]@{name=[IO.Path]::GetFileName($tp);source_sha256=$h2;published_sha256=(H $td);sanitized=$false})}|ConvertTo-Json -Depth 8|Set-Content $man -Encoding UTF8;[ordered]@{schema=5;synced_at_utc=[DateTime]::UtcNow.ToString('o');run_id=$run;path=$rel;fingerprint=$fp;reason='GENERIC_FINAL_VALIDATED';files=@($sf.Name,[IO.Path]::GetFileName($tp),'sync_manifest.json')}|ConvertTo-Json -Depth 6|Set-Content (Join-Path $ResultsClone 'backtests\inbox\LATEST.json') -Encoding UTF8;GR -GitArgs @('-C',$ResultsClone,'config','user.name','Guardian Backtest Bot')|Out-Null;GR -GitArgs @('-C',$ResultsClone,'config','user.email','guardian-backtest@local')|Out-Null;GR -GitArgs @('-C',$ResultsClone,'add','backtests/inbox')|Out-Null;GR -GitArgs @('-C',$ResultsClone,'commit','-m',"Auto-sync validated $fam CSV $run")|Out-Null;GR -GitArgs @('-C',$ResultsClone,'push','origin',$ResultsBranch)|Out-Null;MP $state $fp;Health 'OK' "PUSH OK $run" $sf.Name;Log "PUSH OK | $run | source=$($v.Final.source_name) | rows=$($v.Closed)"}
function Cycle{$state=LS;$start=[DateTime]::Parse($state.watch_start_utc).ToUniversalTime();$fs=@(Get-ChildItem $CommonFiles -File -Filter 'D*_STATS.csv' -ErrorAction SilentlyContinue|Where-Object{$_.Name -match '^D\d{3}_V.+_STATS\.csv$' -and $_.LastWriteTimeUtc -ge $start}|Sort-Object LastWriteTimeUtc);if($fs.Count -eq 0){Health 'WAITING_OUTPUTS' 'No new finalized Dxxx STATS/TRADES pair yet.';return};foreach($sf in $fs){$tn=$sf.Name -replace '_STATS\.csv$','_TRADES.csv';$tp=Join-Path $CommonFiles $tn;if(Test-Path $tp){try{Pub $sf $tp $state}catch{Health 'ERROR_RETRYING' $_.Exception.Message $sf.Name;Log "ERROR | $($sf.Name) | $($_.Exception.Message)"}}}}
function StopPid([string]$p){if(Test-Path $p){try{Stop-Process -Id ([int](Get-Content $p -Raw)) -Force -ErrorAction SilentlyContinue}catch{};Remove-Item $p -Force -ErrorAction SilentlyContinue}}
if($Uninstall){StopPid $PidFile;Remove-Item $StartupCmd -Force -ErrorAction SilentlyContinue;Write-Host 'Guardian generic AutoSync v2.01 uninstalled.';exit}
if($Install){New-Item -ItemType Directory -Force -Path $InstallDir,$StartupDir|Out-Null;Copy-Item $PSCommandPath $InstalledFile -Force;foreach($p in $OldPid){StopPid $p};foreach($p in $OldStartup){Remove-Item $p -Force -ErrorAction SilentlyContinue};StopPid $PidFile;[ordered]@{schema=2;watch_start_utc=[DateTime]::UtcNow.AddSeconds(-5).ToString('o');published_fingerprints=@()}|ConvertTo-Json|Set-Content $StateFile -Encoding UTF8;$cmd='@echo off'+[Environment]::NewLine+'powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File "'+$InstalledFile+'"';Set-Content $StartupCmd $cmd -Encoding ASCII;Start-Process powershell.exe -WindowStyle Hidden -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',$InstalledFile);Write-Host "INSTALLE: $InstalledFile";Write-Host "AUTOSTART: $StartupCmd";Write-Host "HEALTH: $HealthFile";Write-Host "LOG: $LogFile";exit}
$created=$false;$mutex=New-Object Threading.Mutex($true,'Global\GuardianBacktestCSVAutoSyncV201',[ref]$created);if(-not$created){exit};try{Set-Content $PidFile $PID -Encoding ASCII;Health 'STARTING' 'Generic watcher started.';Log "START | pid=$PID | common=$CommonFiles";if($Once){Cycle}else{while($true){Cycle;Start-Sleep $PollSeconds}}}finally{Remove-Item $PidFile -Force -ErrorAction SilentlyContinue;$mutex.ReleaseMutex();$mutex.Dispose();Log 'STOP'}
